executor:
  name: python
  options:
    entry: __init__.py
inputs_def:
  - handle: source_file
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        excludeAll: true
        filters:
          - name: EPUB
            extensions:
              - .epub
  - handle: translated_file
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        excludeAll: true
        filters:
          - name: EPUE
            extensions:
              - .epub
    value:
    nullable: true
  - handle: language
    json_schema:
      enum:
        - zh-Hans
        - zh-Hant
        - en
        - fr
        - de
        - es
        - ru
        - it
        - pt
        - ja
        - ko
      ui:options:
        labels:
          - Simplified Chinese
          - Traditional Chinese
          - English
          - French
          - German
          - Spanish
          - Russian
          - Italian
          - Portuguese
          - Japanese
          - Korean
    value: zh-Hans
  - handle: prompt
    json_schema:
      type: string
      ui:widget: text
    value:
    nullable: true
  - group: LLM
    collapsed: true
  - handle: max_chunk_tokens
    json_schema:
      type: integer
    value: 2048
  - handle: threads
    json_schema:
      type: integer
      minimum: 1
    value: 4
  - handle: retry_times
    json_schema:
      type: integer
      minimum: 1
    value: 5
  - handle: retry_interval_seconds
    json_schema:
      type: number
      minimum: 0
    value: 6.5
  - handle: model
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: oomol-chat
      temperature: 0
      top_p: 0.5
      max_tokens: 4096
outputs_def:
  - handle: translated_file
    json_schema:
      type: string
      ui:widget: save
      ui:options:
        filters:
          - name: EPUB
            extensions:
              - .epub
title: Translate a book
