inputs_def:
  - handle: file
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: title
    json_schema:
      type: string
    value:
    nullable: true
  - handle: max_translating_group
    json_schema:
      type: integer
      minimum: 1
    value: 1000
    nullable: false
  - handle: source
    json_schema:
      type: string
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    value: en
  - handle: target
    json_schema:
      type: string
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    value: cn
  - handle: timeout
    json_schema:
      type: number
      minimum: 0
    value: 0
  - handle: llm
    json_schema:
      ui:options:
        title: Model
      ui:widget: llm::model
    value:
      model: deepseek-chat
      temperature: 1
      top_p: 0.8
      max_tokens: 4096
outputs_def:
  - handle: binary
    description: Output
    json_schema:
      contentMediaType: oomol/bin
icon: ":twemoji:orange-book:"
ui:
  default_width: 478
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate epub book
