inputs_def:
  - handle: file
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: title
    json_schema:
      type: string
  - handle: max_translating_group
    json_schema:
      type: integer
      minimum: 1
    value: 2000
    nullable: false
  - handle: max_translating_group_unit
    json_schema:
      enum:
        - char
        - token
      ui:options:
        labels:
          - Character
          - Token
    value: token
  - handle: ai
    json_schema:
      type: string
      enum:
        - DeepSeek
        - OpenAI
    value: DeepSeek
  - handle: ai_token
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: source
    json_schema:
      type: string
      enum:
        - en
        - cn
      ui:options:
        labels:
          - English
          - 中文
    value: English
  - handle: target
    json_schema:
      type: string
      enum:
        - en
        - cn
      ui:options:
        labels:
          - English
          - 中文
    value: cn
outputs_def:
  - handle: bin
    description: Output
    json_schema:
      type: string
icon: ":twemoji:closed-book:"
ui:
  default_width: 478
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate epub book
