inputs_def:
  - handle: file
    description: Input
    json_schema:
      type: string
      ui:widget: file
  - handle: title
    json_schema:
      type: string
  - handle: max_translating_group
    json_schema:
      type: integer
      minimum: 1
    value: 1000
    nullable: false
  - handle: source
    json_schema:
      type: string
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    value: en
  - handle: target
    json_schema:
      type: string
      enum:
        - en
        - cn
        - ja
        - fr
        - ru
        - de
      ui:options:
        labels:
          - English
          - 中文
          - 日本語
          - Français
          - Русский
          - Deutsch
    value: cn
  - handle: llm_api
    json_schema:
      enum:
        - oomol
        - openai
        - claude
        - Gemini
      ui:options:
        labels:
          - OOMOL
          - OpenAI
          - Claude
          - gemini
    value: oomol
  - handle: model
    json_schema:
      type: string
      minLength: 1
    value:
    nullable: true
  - handle: url
    json_schema:
      type: string
      minLength: 1
    value:
    nullable: true
  - handle: api_key
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value:
    nullable: true
  - handle: temperature
    json_schema:
      type: number
      minimum: 0
    value: 0.4
    nullable: false
  - handle: timeout
    json_schema:
      type: number
      minimum: 0
    value: 0
outputs_def:
  - handle: binary
    description: Output
    json_schema:
      contentMediaType: oomol/bin
icon: ":twemoji:orange-book:"
ui:
  default_width: 478
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate epub book
