inputs_def:
  - handle: file
    description: Input
    json_schema:
      type: string
      ui:widget: file
    value: ""
  - handle: title
    json_schema:
      type: string
  - handle: max_paragraph_characters
    json_schema:
      type: integer
      minimum: 1
      maximum: 5000
    value: 400
  - handle: ai
    json_schema:
      type: string
      enum:
        - DeepSeek
        - OpenAI
    value: DeepSeek
  - handle: ai_token
    json_schema:
      contentMediaType: oomol/secret
      type: string
  - handle: source
    json_schema:
      type: string
      enum:
        - English
        - 中文
    value: English
  - handle: target
    json_schema:
      type: string
      enum:
        - English
        - 中文
    value: 中文
outputs_def:
  - handle: bin
    description: Output
    json_schema:
      type: string
icon: ":fa6-solid:book-open:currentColor:"
ui:
  default_width: 478
executor:
  name: python
  options:
    entry: __init__.py
    spawn: false
title: Translate epub book
